---
name: Check changelog
"on":
  workflow_call: null
jobs:
  changelog:
    runs-on: vcc-azure-ubuntu-latest
    name: Requires changelog
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-changelog')"
    steps:
      - name: Checkout the collection repository
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: "0"
      - name: Validate changelog
        uses: >-
          ansible/ansible-content-actions/.github/actions/ansible_validate_changelog@main
