---
name: Ansible sanity
"on":
  workflow_call: null
jobs:
  tox-matrix:
    name: Matrix Sanity
    runs-on: vcc-azure-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{github.event.pull_request.head.ref}}"
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: "Install tox-ansible, includes tox"
        run: "python -m pip install git+https://github.com/ansible/tox-ansible.git"
      - name: "Check for tox-ansible.ini file, else add default"
        uses: styxxen21/ansible-content-actions/.github/actions/add_tox_ansible@main
      - name: Generate matrix
        id: generate-matrix
        run: >
          python -m tox --ansible --gh-matrix --matrix-scope sanity --conf
          tox-ansible.ini
    outputs:
      envlist: "${{ steps.generate-matrix.outputs.envlist }}"
  test:
    needs: tox-matrix
    strategy:
      fail-fast: false
      matrix:
        entry: "${{ fromJson(needs.tox-matrix.outputs.envlist) }}"
    name: "${{ matrix.entry.name }}"
    runs-on: vcc-azure-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.entry.python }}"
      - name: "Install tox-ansible, includes tox"
        run: python -m pip install tox-ansible
      - name: "Check for tox-ansible.ini file, else add default"
        uses: styxxen21/ansible-content-actions/.github/actions/add_tox_ansible@main
      - name: Run tox sanity tests
        run: >-
          python -m tox --ansible -e ${{ matrix.entry.name }} --conf
          tox-ansible.ini
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
